server:
  port: 8081
spring:
  application:
    name: twitter-clone-posts-service
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://localhost:27017/tc_posts_db}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:1234}
followers-service:
  url: ${FOLLOWERS_URL:http://localhost:8084/followers}
users-service:
  url: ${USERS_URL:http://localhost:8080/users}
service-bus:
  connection-string: ${CONNECTION_SEND_NOTIFICATION}
  topic-name: send-notifications
  #queue-name: ${SB_QUEUE_NAME}
