server:
  port: 8081
spring:
  application:
    name: twitter-clone-posts-service
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: mongodb://localhost:27017/tc_posts_db
follower-service:
  url: ${FOLLOWER_URL:http://localhost:8084/followers}
user-service:
  url: ${USER_URL:http://localhost:8080/users}
