server:
  port: 8081
spring:
  application:
    name: twitter-clone-posts-service
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: mongodb://localhost:27017/tc_posts_db
followers-service:
  url: ${FOLLOWER_URL:http://localhost:8084/followers}
users-service:
  url: ${USER_URL:http://localhost:8080/users}
service-bus:
  connection-string: ${CONNECTION_SEND_NOTIFICATION_POST}
  topic-name: send-notifications
  #queue-name: ${SB_QUEUE_NAME}
